public virtual class ClassInterface {
    
    public virtual List<SObject> handle(){ return new List<SObject>();}

    public virtual Map<String, PrescreenServiceHelper.InspectionWrapper> handle(Map<String, PrescreenServiceHelper.InspectionWrapper> wrapperMap, CR_Review_Trigger__mdt crt){return new Map<String, PrescreenServiceHelper.InspectionWrapper>();}

    public virtual List<SObject> handle(List<SObject> objList){ return new List<SObject>();}
}