public class ConditionReportTriggerHandler extends triggerHandler{
    
    // protected override void afterInsert(){
    //     AssignmentManagerVehicleUpdate.updateRelatedVehicleAndEvent(Trigger.new);
    //     AssignmentManagerVehicleUpdate.checkForReadyToLaunch(Trigger.new, Trigger.oldMap);
    // } 

    // protected override void afterUpdate(){
    //     AssignmentManagerVehicleUpdate.checkForReadyToLaunch(Trigger.new, Trigger.oldMap);
    // }
}